[build]
  command = "CI=false npm run build"
  publish = "build"

[build.environment]
  REACT_APP_API_URL = "https://family-budget-api.onrender.com/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
